# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 027b156d1c14d945c8267ec7267fe87aa44853b7ba00531962329b528161532e8bf34f723c138acd1f71c5c4310768710eb96895d5b77903e6c10316f66db69c

test:
  secret_key_base: b2c5a9da7bc866ca82b43668ba6b5193363ba4a633830c17faf1c3749aaf5f7fab6bf54fb54221c073787bb899d4f9ac340a5abb0d080fc944d3253fdb096754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
